import { expect, test } from '@playwright/test'

test.describe('public acquisition workflow', () => {
  test('landing page and early access page render', async ({ page }) => {
    await page.goto('/landing-page')
    await expect(page.locator('body')).toContainText('Guatemala Rewards')
    await expect(page.getByRole('heading', { name: /Scan once\. Join locally\. Earn rewards|Escanea una vez\. Unete localmente\. Gana recompensas/i })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Partner QR sticker rollout' })).toHaveCount(0)
    await expect(page.getByRole('heading', { name: /One sticker code per partner business|Un codigo de sticker por cada negocio aliado/i })).toHaveCount(0)
    await expect(page.getByRole('heading', { name: /How it works|Cómo funciona/i })).toBeVisible()
    await expect(page.getByRole('heading', { name: /Frequently asked questions|Preguntas frecuentes/i })).toBeVisible()
    await expect(page.getByRole('link', { name: /Businesses|Negocios/i })).toHaveAttribute('href', '/business')
    const joinLink = page.getByRole('link', { name: /Join Guatemala Rewards|Unete a Guatemala Rewards/i }).first()
    await expect(joinLink).toHaveAttribute('href', '/join')
    await joinLink.click()
    await expect(page).toHaveURL(/\/join$/)
    await expect(page.getByRole('textbox', { name: /Full name|Nombre completo/i })).toBeVisible()
    await expect(page.getByRole('button', { name: /Create my account|Crear mi cuenta/i })).toBeVisible()

    await page.goto('/invitation')
    await expect(page.locator('body')).toContainText('Guatemala Rewards')
    await expect(page.locator('body')).toContainText(/highest-paying rewards program|programa de recompensas que mas paga/i)
    await expect(page.locator('body')).toContainText(/Suscribirse|Subscribe/i)
    await page.getByRole('button', { name: /Suscribirse|Subscribe/i }).click()
    const dialog = page.getByRole('dialog')
    await expect(dialog.getByRole('heading', { name: /Join early access|Unirse al acceso temprano/i })).toBeVisible()
    await dialog.getByRole('button', { name: /Suscribirse|Subscribe/i }).click()
    await expect(dialog.getByText(/Enter your name|Ingresa tu nombre/i)).toBeVisible()
    await expect(dialog.getByText(/Enter your WhatsApp number|Ingresa tu n.mero de WhatsApp/i)).toBeVisible()
    await expect(dialog.getByText(/Enter your email|Ingresa tu correo/i)).toBeVisible()
  })
})
